name: Unit tests && deploy (dev)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages && run tests
        run: npm install && npm run test:cov

      - name: Deploy Railway
        run: npm i -g @railway/cli && railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}

    # - uses: actions/checkout@v2
    # - name: Use NodeJS ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - run: |
    #     npm i
    #     npm run test:cov